# Generated by Django 5.0.4 on 2024-04-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='isRestaurant',
            field=models.BooleanField(default=False),
        ),
    ]
