# Generated by Django 5.0.4 on 2024-04-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_restaurantuserrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Out for delivery', max_length=1000),
        ),
    ]
